ignore:
  - vulnerability: CVE-2023-24998
    package:
      name: commons-fileupload
      version: 1.3.3

  - vulnerability: GHSA-hfrx-6qgj-fp6c
    package:
      name: commons-fileupload
      version: 1.3.3

  - vulnerability: GHSA-78wr-2p64-hpwj
    package:
      name: commons-io
      version: 2.7

  - vulnerability: CVE-2011-5034
    package:
      name: geronimo-activation_1.1_spec
      version: 1.1

  - vulnerability: CVE-2011-5034
    package:
      name: geronimo-jta_1.1_spec
      version: 1.1

  - vulnerability: CVE-2011-5034
    package:
      name: geronimo-stax-api_1.0_spec
      version: 1.0.1

  - vulnerability: CVE-2011-5034
    package:
      name: geronimo-ws-metadata_2.0_spec
      version: 1.1.2

  - vulnerability: GHSA-hw42-3568-wj87
    package:
      name: google-oauth-client
      version: 1.21.0

  - vulnerability: GHSA-f263-c949-w85g
    package:
      name: google-oauth-client
      version: 1.21.0

  - vulnerability: CVE-2023-2976
    package:
      name: guava
      version: 19.0

  - vulnerability: GHSA-jjjh-jjxp-wpff
    package:
      name: jackson-databind
      version: 2.13.2.2

  - vulnerability: CVE-2022-42004
    package:
      name: jackson-databind
      version: 2.13.2.2

  - vulnerability: GHSA-rgv9-q543-rqg4
    package:
      name: jackson-databind
      version: 2.13.2.2

  - vulnerability: GHSA-h4x4-5qp2-wp46
    package:
      name: jackson-datatype-jsr310
      version: 2.8.3

  - vulnerability: GHSA-6qvw-249j-h44c
    package:
      name: jose4j
      version: 0.4.4

  - vulnerability: GHSA-4jq9-2xhw-jpx7
    package:
      name: json
      version: 20201115
      
  - vulnerability: GHSA-3vqj-43w4-2q58
    package:
      name: json
      version: 20201115

  - vulnerability: GHSA-vmq6-5m68-f53m
    package:
      name: logback-classic
      version: 1.2.10

  - vulnerability: GHSA-vmq6-5m68-f53m
    package:
      name: logback-core
      version: 1.2.10

  - vulnerability: GHSA-w77p-8cfg-2x43
    package:
      name: slf4j-ext
      version: 1.6.3

  - vulnerability: GHSA-3mc7-4q67-w48m
    package:
      name: snakeyaml
      version: 1.15

  - vulnerability: GHSA-rvwf-54qp-4r6v
    package:
      name: snakeyaml
      version: 1.15

  - vulnerability: GHSA-mjmj-j48q-9wg2
    package:
      name: snakeyaml
      version: 1.15

  - vulnerability: GHSA-pv39-qp28-4mgh
    package:
      name: soa-model-core
      version: 1.6.0

  - vulnerability: CVE-2018-1270
    package:
      name: spring-core
      version: 4.2.3.RELEASE

  - vulnerability: CVE-2016-1000027
    package:
      name: spring-core
      version: 4.2.3.RELEASE

  - vulnerability: CVE-2022-22965
    package:
      name: spring-core
      version: 4.2.3.RELEASE

  - vulnerability: CVE-2017-1000208
    package:
      name: swagger-parser
      version: 1.0.23

  - vulnerability: CVE-2017-1000207
    package:
      name: swagger-parser
      version: 1.0.23

  - vulnerability: GHSA-vgvf-9jh3-fg75
    package:
      name: swagger-parser
      version: 1.0.23

  - vulnerability: GHSA-q7pf-qr96-2vq5
    package:
      name: swagger-parser
      version: 1.0.23

  - vulnerability: CVE-2022-40152
    package:
      name: woodstox-core
      version: 5.0.3
